---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Zsh
  apt: name=zsh state=installed

- name: Change default shell
  user: name={{ item }} shell=/bin/zsh
  with_items: zsh_users
